FROM 475911326710.dkr.ecr.ap-northeast-1.amazonaws.com/node:20.13.1-slim as build

WORKDIR /zklink-intent-url

RUN apt update -y

RUN apt install -y python-is-python3

ADD . /zklink-intent-url

RUN npm install

RUN npm run build && cd -

FROM 475911326710.dkr.ecr.ap-northeast-1.amazonaws.com/node:20.13.1-slim

RUN mkdir /zklink-intent-url

#RUN npm install -g npm@10.8.2

COPY --from=build /zklink-intent-url /zklink-intent-url

WORKDIR /zklink-intent-url

CMD ["/bin/sh", "-c", "npm run migration:run && npm run start"]
